project:
  type: website

website:
  title: "spdev-blogs"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/souradipp76/
      - icon: twitter
        href: https://twitter.com/souradip_pal96/
format:
  html:
    theme: cosmo
    css: styles.css



